### ISSUE TITLE
Moving forward

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#72]
Note that currently, CI depends on the `progress` branch of `python-shader`. Although both projects do not depend on each-other, both the CI's do :) The plan to move forward:

* [x] Merge https://github.com/almarklein/wgpu-py/pull/71
* [x] Perhaps a bit more work on wgpu-py
  * [x] Improve api coverage #74
  * [x] Implement indirect drawing #75
  * [x] Use one API for defining shader inputs #76
* [x] Release wgpu-py
* [x] Merge https://github.com/almarklein/python-shader/pull/22
* [x] Perhaps a bit more work on python-shader
  * [x] Allow just one API for defining shader inputs https://github.com/almarklein/python-shader/pull/26
  * [x] More consistent exceptions
  * [x] More examples and validate them on CI
  * [x] Docs in readme 
* [x] Release python-shader
* [x] Remove wgpu-py's pip install from git
* [x] More work on wgpu-py
  * [x] Update to latest wgpu-bin and webgpu #77  
  * [x] Canvas update method #63 #78
   * [x] Re-evaluate #25
  * [x] Docs #13 #79 #80
  * [x] Update readme #80
  * [x] Update wgpu-bin to wgpu-native v0.5.1
  * [x] Update wgpu-py to v0.5.1 #81
  * [x] Rework `request_adapter` and swap chain w.r.t. surface id. #83
  * [x] Have another quick look at #73
  * [x] Implement debug markers #84
* [x] Yet more work on wgpy-py :)
  * [x] Fixes for linux #85 
  * [x] Untangle the API from canvas gui details #87
  * [x] Fix the grayscale texture issue #89 
  * [x] Implement optional/defaults where IDL has them #91
* [x] Also some fixes in python-shader
* [x] New release of python-shader
* [x] New release of wgpu-py
* [ ] Finally get to work on visvis2 🤣

**Comment by Korijn** [comment]
Nice work on the docs! The GUI API page left me a little confused though; where are the calls to `request_draw`?

**Comment by Korijn** [comment]
Woohoo! :rocket:
